// <auto-generated />
namespace Employee_Management_Peoject.Migrations.EmployeeDB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ScriptL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ScriptL));
        
        string IMigrationMetadata.Id
        {
            get { return "202402031606155_ScriptL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
